# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'CustomUIComponentsTest' do
    pod 'SnapKit', '~> 5.0.0'
end
